name: Metrics
on:
  # Schedule updates (every night)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Personal metrics (left)
        uses: tasyiann/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-left.svg
          plugin_isocalendar: yes

