name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Personal metrics (left)
        uses: tasyiann/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-left.svg
          plugin_isocalendar: yes

      - name: Personal metrics (right)
        uses: tasyiann/metrics@master
        with:
          filename: metrics-right.svg
          token: NOT_NEEDED
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: Europe/Athens # Set timezone
          plugin_rss: yes
          plugin_rss_source: https://500px.com/ayiann/rss  # RSS feed
          plugin_rss_limit: 3                              # Limit to 6 items
          
          

